"""
Django settings for menitmeter_clone project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# mentimeter_clone/settings.py

import os
from pathlib import Path

# مسیر پایه پروژه
BASE_DIR = Path(__file__).resolve().parent.parent

# امنیت
SECRET_KEY = 'django-insecure-vs9@obd6(0vax)o6l*h^)8#-&a1v0frggu_w$zl@uf$51*qj5t'
DEBUG = True  # در محیط تولید به False تغییر دهید
ALLOWED_HOSTS = []  # در محیط تولید، دامنه‌های مجاز را اضافه کنید

# اپلیکیشن‌ها
INSTALLED_APPS = [
    # اپلیکیشن‌های پیش‌فرض Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # اپلیکیشن‌های سفارشی
    'core',
]

# میان‌افزارها
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# روت URLها
ROOT_URLCONF = 'mentimeter_clone.urls'

# تنظیمات قالب‌ها
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'core', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # پردازش‌کننده‌های پیش‌فرض
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI
WSGI_APPLICATION = 'mentimeter_clone.wsgi.application'

# پایگاه داده
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # برای محیط تولید، از پایگاه داده‌های دیگر استفاده کنید
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# احراز هویت سفارشی
AUTH_USER_MODEL = 'core.User'

# پسورد
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # سایر ولیداتورها
]

# زبان و منطقه زمانی
LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# استاتیک و مدیا
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# احراز هویت
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# کلید‌های API
KAVENEGAR_API_KEY = 'your-kavenegar-api-key'
ZARINPAL_MERCHANT_ID = 'your-zarinpal-merchant-id'

# کشینگ
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# ایمیل (اختیاری، برای ارسال ایمیل‌های سیستم)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.your-email.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'your-email@domain.com'
EMAIL_HOST_PASSWORD = 'your-password'
EMAIL_USE_TLS = True

# امنیت SSL (در محیط تولید باید فعال شود)
SECURE_SSL_REDIRECT = False  # در محیط تولید به True تغییر دهید
SESSION_COOKIE_SECURE = False  # در محیط تولید به True تغییر دهید
CSRF_COOKIE_SECURE = False  # در محیط تولید به True تغییر دهید

# جلوگیری از حملات XSS
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# محتوای ایمن
SECURE_CONTENT_TYPE_NOSNIFF = True
